# Generated by Django 2.2.5 on 2020-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='calibration_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Calibration Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
