# Generated by Django 2.2.5 on 2020-01-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('account_code', models.CharField(max_length=10, verbose_name='Account Code')),
                ('internal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Internal Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', max_length=50)),
                ('updated_by', models.CharField(default='Admin', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100, verbose_name='Entity Name')),
                ('entity_abbreviation', models.CharField(blank=True, max_length=15, null=True, verbose_name='Abbreviation')),
                ('entity_type', models.CharField(choices=[('SEC', 'Section'), ('DIV', 'Division'), ('DEP', 'Department'), ('BRA', 'Branch')], default='SEC', max_length=4, verbose_name='Entity Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', max_length=50)),
                ('updated_by', models.CharField(default='Admin', max_length=50)),
                ('account', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.Account')),
            ],
            options={
                'verbose_name_plural': 'Entaties',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('PS', 'Postall'), ('BL', 'Billing'), ('PY', 'Physical'), ('CL', 'Collection'), ('CL', 'Delivery'), ('CD', 'Collection/Delivery')], default='PY', max_length=4, verbose_name='Address Type')),
                ('address_l1', models.CharField(max_length=100, verbose_name='Street Address')),
                ('address_l2', models.CharField(max_length=100, verbose_name='Building')),
                ('address_l3', models.CharField(max_length=100, verbose_name='Room Number')),
                ('suburb', models.CharField(max_length=50, verbose_name='Suburb')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('province', models.CharField(choices=[('EC', 'Easter Cape'), ('FS', 'Free State'), ('GT', 'Gauteng'), ('NL', 'Kwazulu-Natal'), ('LP', 'Limpopo'), ('MP', 'Mpumalanga'), ('NC', 'Northern Cape'), ('NW', 'North West'), ('WC', 'Western Cape')], default='GT', max_length=4, verbose_name='Province')),
                ('code', models.CharField(max_length=4, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', max_length=50)),
                ('updated_by', models.CharField(default='Admin', max_length=50)),
                ('entity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.Entity')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
