# Generated by Django 2.2.5 on 2020-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200128_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Account Code'),
        ),
    ]
