# Generated by Django 2.2.5 on 2020-01-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, verbose_name='Serial Number')),
                ('internal_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tag Number')),
                ('date_installed', models.DateField(blank=True, null=True, verbose_name='Data Installed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', max_length=50)),
                ('updated_by', models.CharField(default='Admin', max_length=50)),
                ('entity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.Entity')),
                ('equipment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
            options={
                'verbose_name_plural': 'Instruments',
            },
        ),
    ]
