# Generated by Django 2.2.5 on 2020-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='equipment_card_no',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Equipment Card # (SAP)'),
        ),
    ]
