# Generated by Django 2.2.5 on 2020-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
